# Generated by Django 5.0.7 on 2024-07-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bus", "0001_initial"),
    ]

    operations = []
