# Generated by Django 5.0.7 on 2024-07-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus", "0002_auto_20240718_2146"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journey",
            options={"ordering": ("departure_time",)},
        ),
        migrations.AddField(
            model_name="ticket",
            name="email",
            field=models.EmailField(default="", max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
