# Generated by Django 5.0.7 on 2024-07-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus", "0003_alter_journey_options_ticket_email_ticket_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
